services:
  apex-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_CLIENT_ID=apex-api
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - kafka
      - redis
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - apex-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - apex-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
    depends_on:
      - zookeeper
    networks:
      - apex-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - apex-network

networks:
  apex-network:
    driver: bridge